[2025-04-08T21:37:53.474+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-08T21:37:53.486+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: postgres_pipeline.insert_season_data scheduled__2025-04-08T21:36:00+00:00 [queued]>
[2025-04-08T21:37:53.494+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: postgres_pipeline.insert_season_data scheduled__2025-04-08T21:36:00+00:00 [queued]>
[2025-04-08T21:37:53.495+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-08T21:37:53.502+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): insert_season_data> on 2025-04-08 21:36:00+00:00
[2025-04-08T21:37:53.507+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=22846) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-08T21:37:53.508+0000] {standard_task_runner.py:72} INFO - Started process 22849 to run task
[2025-04-08T21:37:53.507+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'postgres_pipeline', 'insert_season_data', 'scheduled__2025-04-08T21:36:00+00:00', '--job-id', '973', '--raw', '--subdir', 'DAGS_FOLDER/dag_postgres.py', '--cfg-path', '/tmp/tmpmekluukr']
[2025-04-08T21:37:53.509+0000] {standard_task_runner.py:105} INFO - Job 973: Subtask insert_season_data
[2025-04-08T21:37:53.538+0000] {task_command.py:467} INFO - Running <TaskInstance: postgres_pipeline.insert_season_data scheduled__2025-04-08T21:36:00+00:00 [running]> on host 970813cff045
[2025-04-08T21:37:53.582+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='postgres_pipeline' AIRFLOW_CTX_TASK_ID='insert_season_data' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T21:36:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-08T21:36:00+00:00'
[2025-04-08T21:37:53.584+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-08T21:37:53.596+0000] {base.py:84} INFO - Retrieving connection 'postgres_local'
[2025-04-08T21:37:53.609+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-08T21:37:53.616+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-08T21:37:53.617+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=postgres_pipeline, task_id=insert_season_data, run_id=scheduled__2025-04-08T21:36:00+00:00, execution_date=20250408T213600, start_date=20250408T213753, end_date=20250408T213753
[2025-04-08T21:37:53.648+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-08T21:37:53.661+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T21:37:53.662+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
